export const themeList = [
    'Accounting & Finance',
    'Advertising',
    'Agriculture',
    'Apiology',
    'Arachnology',
    'Arthropodology',
    'Architecture',
    'Bioscience',
    'Botany',
    'Business Research',
    'Cetology',
    'Chemistry',
    'Commerce',
    'Computer Application',
    'Consumer Behaviour & Relationship Management',
    'Corporate Governance',
    'Earth Sciences',
    'Economics',
    'E-commerce',
    'Education',
    'Engineering & Technology',
    'Entrepreneurship',
    'Fisheries',
    'Fine Art',
    'Geography',
    'Health Care',
    'Helminthology',
    'Herpetology',
    'History',
    'Human Resources Management',
    'Ichthyology',
    'Industrial Relations',
    'Information Technology',
    'International Business',
    'Law / Criminology',
    'Library Science',
    'Life Sciences',
    'Logistics and Supply Chain Management',
    'Malacology',
    'Marketing communication',
    'Marketing Management',
    'Mathematics',
    'Medical Sciences',
    'Medicine',
    'Microbiology',
    'Mosquito Taxonomical Studies',
    'Music',
    'Myrmecology',
    'Nematology',
    'Neuroethology',
    'Nursing / Pharmacy',
    'Nutraceuticals',
    'Performing Arts',
    'Philosophy',
    'Physics',
    'Political Sciences',
    'Population Studies',
    'Primatology',
    'Psychology',
    'Renewable Energy',
    'Selling and Marketing techniques',
    'Social Science',
    'Sociology',
    'Strategic Management',
    'Total Quality Management Training and Development',
    'Vector (Mosquito) Biology',
    'Vector Competence of Vector-Borne Diseases',
    'Vector Ecology',
    'Vector Molecular Biology',
    'Veterinary Sciences',
    'Zoology',
    'Zooarchaeology, etc.'
];
